---
- name: this playbook installs httpd
  hosts: webservers
  become: true
  tasks:
  - name: install package
    yum:
        name: httpd
        state: installed
    when: ansible_os_family == "RedHat"
  - name: start apache
    service:
      name: httpd
      state: started
    when: ansible_os_family == "RedHat"
    ignore_errors: yes
    # we can assume here that there was some error while starting the application but if we still want to proceed with the tasks then we need to use ignore errors.

  - name: install apache2
    apt:
      name: apache2
      state: present
    when: ansible_os_family == "Debian"
  - name: start apache2
    service:
      name: apache2
      state: started
    when: ansible_os_family == "Debian"
  - name: Copying test index.html
    copy:
      src: /home/ansadmin/test.html
      dest: /var/www/html
      mode: 0666
      owner: root
      group: root