---
- name: Install nginx
  hosts: all
  become: true
  tasks:
    - name: Install nginx
      yum:
        name: nginx
        state: present
    - name: Start Service
      service:
         name: nginx
         state: started