---
- name: install apache2 on ubuntu server
  hosts: node2
  become: true
  tasks:
    - name: Install apache httpd
      apt:
        name: apache2
        state: present
      notify: start apache2
  handlers:
    - name: start apache2
      service:
        name: apache2
        state: started