# tasks are used only when a particular type of tasks needs to be segregated from some other type of tasks.
---
- name: this playbook installs httpd
  hosts: webservers
  become: true
  tasks:
  - name: install package
    yum:
        name: httpd
        state: installed
    when: ansible_os_family == "RedHat"
    tags: install_apache
  - name: start apache
    service:
      name: httpd
      state: started
    when: ansible_os_family == "RedHat"
    tags: start_apache
  - name: install apache2
    apt:
      name: apache2
      state: present
    when: ansible_os_family == "Debian"
    tags: install_apache
  - name: start apache2
    service:
      name: apache2
      state: started
    when: ansible_os_family == "Debian"
    tags: start_apache
  - name: Copying test index.html
    copy:
      src: /home/ansadmin/test.html
      dest: /var/www/html
      mode: 0666
      owner: root
      group: root
# here while executing the ansible playbook we will have to specify tags.
# if tags are not specified then the particular playbook will run in a normal way.
# ansible-playbook tags.yaml --tags "install_apache"
# only install packages is done and then copying is done.