# there are variables in ansible which are used a lot.
---
- name: this playbook is to create user
  hosts: all
  become: true
  var:
    user: john
  tasks:
    name: Creating user {{user}}
    user:
      name: '{{user}}'
---
- name: this playbook is to create users
  hosts: all
  become: true
  var_files:
    - user.yaml
  tasks:
    name: Creating user {{user}}
    user:
      name: '{{user}}'
# variables which are passed using the command line has the highest priority