---
- name: Cloning github
  hosts: all
  become: true
  vars_files:
     - vault-pass.yml
  tasks:
    - name: clone a repo
      git:
# here we will be doing the simple cloning of application.
        repo: https://oauth2:<token>@github.com/KunalJoshi15/DSA.git
        dest: /opt/test-vault/